//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Budget.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.TransactionCategories = new HashSet<TransactionCategory>();
        }
    
        public System.Guid Guid { get; set; }
        public string Name { get; set; }
        public double Budgeted { get; set; }
        public Nullable<int> Year { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<TransactionCategory> TransactionCategories { get; set; }
    }
}
