//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Budget.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payee
    {
        public Payee()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public System.Guid Guid { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
