//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Budget.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public Transaction()
        {
            this.TransactionCategories = new HashSet<TransactionCategory>();
        }
    
        public System.Guid Guid { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.Guid> Payee { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.Guid> Account { get; set; }
        public string Notes { get; set; }
        public string CheckNumber { get; set; }
    
        public virtual Account Account1 { get; set; }
        public virtual Payee Payee1 { get; set; }
        public virtual ICollection<TransactionCategory> TransactionCategories { get; set; }
    }
}
